![banner](../banner.jpg)

***[Workshop 4](about) - Training course in data analysis for genomic surveillance of African malaria vectors***

---

# Module 1 - NumPy arrays

**Theme: Tools & technology**

NumPy (Numerical Python) is a Python package for working with numerical data. It is right at the heart of the scientific computing ecosystem in Python, and is a powerful tool for fast and memory-efficient analysis of large genomic datasets. This module introduces NumPy arrays, which are the fundamental data structure that NumPy provides for storing and computing with numerical data. 

This module borrows heavily from [NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html) by the NumPy team and [A visual Intro to NumPy and Data Representation](https://jalammar.github.io/visual-numpy/) by Jay Alammar. 

## Learning objectives

At the end of this module you will be able to:

* Explain why we use NumPy for genomic data analysis.
* Create NumPy arrays.
* Access data in an array using indexing and slicing.
* Perform simple mathematical computations with arrays.
* Perform simple aggregations with arrays.

## Lecture

### English

In [2]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/N0TkJ2KITK0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Français

In [1]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/1IaraoWkySA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Why use NumPy?

In this course we want to perform analyses with large datasets using cloud computing services. Because the datasets are large, we need to be careful about how we use memory (RAM).

We also want to perform those analyses interactively. 

Interactivity means computations need to run quickly, so we don't have to wait and can continue straight on with the next step in our exploration of the data.

Interactivity also means we don't want to spend hours writing complicated code for each step in the analysis. We want simple code that can be written quickly and adapted as needed.

In summary, we want to store numerical data so that:

* **Memory is used efficiently**
* **Computations are fast**
* **Code is simple and concise**

## What is a NumPy array?

A NumPy array is a data structure where the data values are arranged in an N-dimensional grid. Let's look at some examples of data that can be stored using NumPy arrays.



### 1-D array (vector)

An audio recording is an example of data that can be represented as a 1-dimensional (1-D) array. A 1-D array is also sometimes called a "vector".

Here the data values in the array are the amplitude values sampled at regular time intervals, and the first (and only) dimension of the array corresponds to the time at which each audio sample should be played.

<img src="https://jalammar.github.io/images/numpy/numpy-audio.png"/>

### 2-D array (matrix)

A black-and-white image is an example of data that can be represented as a 2-dimensional (2-D) array. A 2-D array is also sometimes called a "matrix".

Here the data values in the array correspond to the colour of a pixel, where 0 represents black, 255 represents white, and numbers in between correspond to shades of grey.

The first dimension of the array corresponds to the vertical position of pixels within the image, and the second dimension corresponds to the horizontal position of the pixels.

<img src="https://jalammar.github.io/images/numpy/numpy-grayscale-image.png"/>

### 3-D array (tensor)

A colour image is an example of data that can be represented as a 3-dimensional (3-D) array. A 3-D array is sometimes also called a "tensor".

Here the data values represent the intensity of each pixel in three separate colour channels - red, green and blue. 

As with the black-and-white image, the first dimension of the array corresponds to the vertical position of pixels within the image, and the second dimension corresponds to the horizontal position of the pixels. Here now there is also a third dimension of length three, which represents the three colour channels.

<img src="https://jalammar.github.io/images/numpy/numpy-color-image.png"/>

Genotype calls are another example of data that can be stored as a 3-D array. 

Here each data value is an allele encoded numerically, where 0 encodes the reference allele, and higher values encode alternate alleles.

The first dimension (rows) corresponds to the positions in the reference genome; the second dimension (columns) corresponds to the individual organisms that were sequenced; and the third dimension corresponds to the ploidy of the organisms (2 for animals such as humans or mosquitoes).

<img src="https://storage.googleapis.com/vo_agam_release/reference/training-images/workshop-4/mosquito-genotype-array.png"/>

## Importing NumPy

On colab, NumPy is already installed, so we can go ahead and import it.

In [3]:
import numpy as np

## Creating an array from existing data

There are various ways to create a NumPy array. One way is to create an array from some existing data, via the [`np.array()`](https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array) function.

### Creating a 1-D array

Let's create a 1-D array storing the data values `[1, 2, 3]`. We'll assign this array to a variable named `data`, but this variable could be named whatever you like.

In [4]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [5]:
type(data)

numpy.ndarray

Here is a visual illustration of the array we just created.

<img src="https://numpy.org/doc/stable/_images/np_array.png"></img>

Every NumPy array has some useful attributes which tell us something about the array.

Here is the number of dimensions:

In [6]:
data.ndim

1

Here is the total number of elements in the array:

In [7]:
data.size

3

Here is the shape of the array, which tells us the lengths of each of the dimensions. This returns a [tuple](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences) of numbers, one length for each dimension. Here there is only one dimension, so we get a tuple of length one.

In [8]:
data.shape

(3,)

Every array also has a data type (dtype) which defines the type of all of the data values.

In [9]:
data.dtype

dtype('int64')

Here "int" means [integer](https://en.wikipedia.org/wiki/Integer), i.e., data values in this array should be interpreted as whole numbers.

### Creating a 2-D array

Let's create a 2-D array with three rows and two columns.

In [10]:
data_2d = np.array([[1, 2], [3, 4], [5, 6]])
data_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

Here is a visual illustration of this 2-D array.

<img src="https://numpy.org/doc/stable/_images/np_create_matrix.png"></img>

Again, let's access the attributes of this array to find out more about it.

In [11]:
data_2d.ndim

2

In [12]:
data_2d.size

6

In [13]:
data_2d.shape

(3, 2)

In [14]:
data_2d.dtype

dtype('int64')

### Creating a 3-D array

Let's now create a 3-D array, with shape (2, 2, 2) - i.e., all dimensions are length 2.

In [15]:
data_3d = np.array([[[1, 2], [3, 4]], 
                    [[5, 6], [7, 8]]])
data_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

<img src="https://jalammar.github.io/images/numpy/numpy-3d-array.png"/>

## Some other array creation functions

Often it is useful to create an array and initialise it such that all data values are set for us by NumPy. There are several functions for doing this, including [`np.ones()`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html), [`np.zeros()`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) and [`np.random.random()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random).

### 1-D arrays

Create an array with all data values initialised to one.

In [16]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [17]:
ones.ndim

1

In [18]:
ones.size

3

In [19]:
ones.shape

(3,)

In [20]:
ones.dtype

dtype('float64')

Note here the dtype is "float64". Here "float" means [floating-point number](https://en.wikipedia.org/wiki/Floating-point_arithmetic#Floating-point_numbers), i.e., the data values should be interpreted as real numbers (i.e., continuous quantities) with some degree of precision.

Similarly, create an array with all data values initialised to zero.

In [21]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

Create an array with data values initialised using a random number generator.

In [22]:
foo = np.random.random(3)
foo

array([0.47496624, 0.0843243 , 0.87849017])

Here are visual illustrations of the three arrays we just created.

<img src="https://numpy.org/doc/stable/_images/np_ones_zeros_random.png"></img>

**Exercise 1 (English)**

Uncomment and run the code cells below to answer the following questions.

What is the number of dimensions of the `foo` array we created above?

What is the number of items (size) of the `foo` array?

What is the shape of the `foo` array?

What is the data type of the `foo` array?

Create an array of ten zeros.

Create an array of one million random numbers.

**Exercice 1 (Français)**

Décommenter et exécuter les cellules de code ci-dessous pour répondre aux questions suivantes.

Combien de dimensions a l'array `foo` que nous avons créé plus haut?

Combien d'objets (taille) l'array `foo` contient-il?

Quel est le type des données de l'array `foo`?

Créer un array contenant dix zéros.

Créer un array contenant un million de nombres aléatoires.

In [23]:
# foo.ndim

In [24]:
# foo.size

In [25]:
# foo.shape

In [26]:
# foo.dtype

In [27]:
# bar = np.zeros(10)
# bar

In [28]:
# baz = np.random.random(1_000_000)
# baz

### 2-D arrays

We can also created 2-D arrays via the same functions, by passing the shape of the desired array as the first parameter.

E.g., create an array with three rows and two columns with all data values initialised to one.

In [29]:
ones_2d = np.ones((3, 2))
ones_2d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

E.g., create an array with three rows and two columns with all data values initialised to zero.

In [30]:
zeros_2d = np.zeros((3, 2))
zeros_2d

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

E.g., create an array with three rows and two columns, initialised with random numbers.

In [31]:
bar = np.random.random((3, 2))
bar

array([[0.37998668, 0.78589495],
       [0.66937203, 0.83885881],
       [0.67516526, 0.3452637 ]])

Here's an illustration of the 2-D arrays we created.

<img src="https://numpy.org/doc/stable/_images/np_ones_zeros_matrix.png"/>

**Exercise 2 (English)**

Create a 2-D array of random numbers with 1,000 rows and 500 columns. Check the values of the `ndim`, `size`, `shape` and `dtype` attributes.

**Exercice 2 (Français)**

Créer un array de dimension 2 contenant 1000 lignes et 500 colonnes de nombres aléatoires. Vérifier les valeurs des attributs `ndim`, `size`, `shape` et `dtype`.

## Accessing elements of an array (indexing and slicing)

The data values of an array can be accessed by using the square bracket notation. Remember that indices start from zero in Python.

### 1-D arrays

In [32]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

<img src="https://numpy.org/doc/stable/_images/np_array.png"></img>

For 1-D arrays, we write a single index in the square brackets.

E.g., access the data value in the first element of the array:

In [33]:
data[0]

1

Access the second element:

In [34]:
data[1]

2

We can also access a contiguous region of an array using the slicing notation, by writing the start and stop indices separated by a colon. Note that this will return a new array. Remember that the start index is included, but the stop index is not.

E.g., access the first two elements:

In [35]:
data[0:2]

array([1, 2])

Access the second and all subsequent elements:

In [36]:
data[1:]

array([2, 3])

Negative indices can also be used, and count backwards from the end of an array.

E.g., access the second from last and all subsequent elements:

In [37]:
data[-2:]

array([2, 3])

Here is an illustration of the array we created, and the results of indexing the array in different ways.

<img src="https://numpy.org/doc/stable/_images/np_indexing.png"/>

**Exercise 3 (English)**

Create a new 1-D array initialised with the data values `[0, 5, 23, 37, 42, 54, 61, 79, 88, 90]`.

Using indexing to access the data value in the fifth element of the array.

Access the final element of the array.

Using slicing to access the third, fourth and fifth elements of the array.

**Exercice 3 (Français)**

Créer un array de dimension 1 contenant les valeurs `[0, 5, 23, 37, 42, 54, 61, 79, 88, 90]`.

Utiliser un index pour accéder à la valeur du cinquième élément de cet array.

Accéder au dernier élément de cet array.

Utiliser une tranche pour accéder au troisième, quatrième et cinquième éléments de cet array.

### 2-D arrays

2-D arrays can also be indexed using the square bracket notation. Here, because there are two dimensions, we need to provide two indices, one for each dimension.

In [38]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

<img src="https://numpy.org/doc/stable/_images/np_create_matrix.png"/>

E.g., access the data value in the first row, second column:

In [39]:
data[0, 1]

2

We can also slice 2-D arrays.

E.g., access the second and all subsequent rows, and all columns:

In [40]:
data[1:3]

array([[3, 4],
       [5, 6]])

To be more explicit, we could also provide the slice we require along the second dimension, i.e., all columns:

In [41]:
data[1:3, :]

array([[3, 4],
       [5, 6]])

Access the first two rows, first column:

In [42]:
data[0:2, 0]

array([1, 3])

Here's an illustration of these indexing operations on a 2-D array:

<img src="https://numpy.org/doc/stable/_images/np_matrix_indexing.png"/>

**Exercise 4 (English)**

Create a new 2-D array initialised with the data values `[[0, 5, 23], [37, 42, 54], [61, 79, 88]]`.

Use indexing to access the data value in second row, third column of the array.

Use slicing to access the first and second rows of the array.

Access the last two values in the second column of the array.

**Exercice 4 (Français)**

Créer un nouvel array de dimension 2 contenant les valeurs `[[0, 5, 23], [37, 42, 54], [61, 79, 88]]`.

Utiliser les indexes pour accéder à la valeur se trouvant à la deuxième ligne, troisième colonne de cet array.

Utiliser une tranche pour accéder à la première et à la seconde ligne de cet array.

Accéder aux deux dernières valeurs de la seconde colonne de cet array.

## Basic mathematical operations with arrays

One of the most powerful features of NumPy arrays is that you can use them to perform mathematical operations. In particular, you can apply mathematical operations between entire arrays, without having to write any `for` loops. Let's see this in action.

### 1-D arrays

To demonstrate, let's create two arrays.

In [43]:
data = np.array([1, 2])
ones = np.ones(2)

<img src="https://numpy.org/doc/stable/_images/np_array_dataones.png"/>

Now, add these two arrays together.

In [44]:
result = data + ones
result

array([2., 3.])

Each element of the `data` array has been added to each element of the `ones` array, to create a new array that we've assigned to the variable named `result`. This is an example of an elementwise computation that NumPy performs for us.

Here's an illustration of this computation:

<img src="https://numpy.org/doc/stable/_images/np_data_plus_ones.png"/>

Similarly, we can subtract, multiply and divide arrays.

In [45]:
data - ones

array([0., 1.])

In [46]:
data * data

array([1, 4])

In [47]:
data / data

array([1., 1.])

<img src="https://numpy.org/doc/stable/_images/np_sub_mult_divide.png"/>

You can also perform arithmetic between arrays and a single number (also known as a scalar). E.g., multiply all values in the `data` array by the number 1.6:

In [48]:
data * 1.6

array([1.6, 3.2])

Here, NumPy has guessed that we want to multiply each element of the `data` array. Do it has "broadcast" the scalar value 1.6 to an array of the same shape as `data`. This is an illustration of what happened:

<img src="https://numpy.org/doc/stable/_images/np_multiply_broadcasting.png"/>

As well as arithmetic, you can also perform comparisons. E.g., compute all values in the `data` array that are greater than one:

In [49]:
result = data > 1
result

array([False,  True])

Note that the result is an array of Boolean values (either True or False).

In [50]:
result.dtype

dtype('bool')

### 2-D arrays

All of the same mathematical operations can be performed with 2-D arrays as well.

E.g., add two arrays:

In [51]:
data = np.array([[1, 2], [3, 4]])
ones = np.ones((2, 2))
data + ones

array([[2., 3.],
       [4., 5.]])

<img src="https://numpy.org/doc/stable/_images/np_matrix_arithmetic.png"/>

E.g., multiply an  array by a scalar:

In [52]:
data * 1.6

array([[1.6, 3.2],
       [4.8, 6.4]])

E.g., compare an array with a scalar:

In [53]:
data > 1

array([[False,  True],
       [ True,  True]])

**Exercise 5 (English)**

Create a new array initialised with the data values `[[0, 5, 23], [37, 42, 54], [61, 79, 88]]`.

Multiply this array by itself.

Add one to every element of this array. 

**Exercice 5 (Français)**

Créer un nouvel array initialisé avec les valeurs `[[0, 5, 23], [37, 42, 54], [61, 79, 88]]`.

Multiplier cet array par lui-même.

Ajouter un à chaque élément de cet array.

## Aggregations

NumPy also provides some aggregation functions, including `max()`, `min()`, `sum()`, and `count_nonzero()`, which you can use with arrays. 

Note that `max()`, `min()` and `sum()` can be called in two different ways: either as methods of an array, or as a function.

### 1-D arrays

Here are examples of aggregation functions used with a 1-D array.

In [54]:
data = np.array([1, 2, 3])

In [55]:
data.max()

3

In [56]:
np.max(data)

3

In [57]:
data.min()

1

In [58]:
data.sum()

6

<img src="https://numpy.org/doc/stable/_images/np_aggregation.png"/>

In [59]:
data > 1

array([False,  True,  True])

In [60]:
np.count_nonzero(data > 1)

2

### 2-D arrays

Here are examples of aggregation functions used with a 2-D array.

In [61]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
data.max()

6

In [63]:
data.min()

1

In [64]:
data.sum()

21

<img src="https://numpy.org/doc/stable/_images/np_matrix_aggregation.png"/>

The `axis` parameter can also be used here to perform aggregation along a dimension of an array.

In [65]:
data.max(axis=0)

array([5, 6])

In [66]:
data.max(axis=1)

array([2, 4, 6])

<img src="https://numpy.org/doc/stable/_images/np_matrix_aggregation_row.png"/>

In [67]:
data > 1

array([[False,  True],
       [ True,  True],
       [ True,  True]])

In [68]:
np.count_nonzero(data > 1)

5

In [69]:
np.count_nonzero(data > 1, axis=1)

array([1, 2, 2])

**Exercise 6 (English)**

Create a 2-D array of random numbers with 4 rows and 3 columns.

Multiply the array by 100.

Find the maximum, minimum and sum of the array.

Find the maximum value in each row.

Find the minimum value in each column.

**Exercice 6 (Français)**

Créer un array de dimension 2 avec 4 lignes et 3 colonnes de nombres aléatoires.

Multiplier cet array par 100.

Trouver le maximum, le minimum et la somme de cet array.

Trouver le maximum de chaque ligne.

Trouver le minimum de chaque colonne.

## Working with mathematical formulas

NumPy can be used to implement mathematical formulas and perform some computation over data of any size.

For example, here is a formula for computing mean square error.

<img src="https://numpy.org/doc/stable/_images/np_MSE_formula.png"/>

To illustrate how we would implement this with NumPy, let's create some data:

In [70]:
predictions = np.array([1, 1, 1])
predictions

array([1, 1, 1])

In [71]:
labels = np.array([1, 2, 3])
labels

array([1, 2, 3])

Now implement the formula to compute the mean square error between `predictions` and `labels`:

In [72]:
n = predictions.size
error = (1/n) * np.sum(np.square(predictions - labels))
error

1.6666666666666665

Here is a visual illustration of how NumPy performs this computation internally.

<img src="https://numpy.org/doc/stable/_images/np_MSE_implementation.png"/>

<img src="https://numpy.org/doc/stable/_images/np_mse_viz1.png"/>

<img src="https://numpy.org/doc/stable/_images/np_mse_viz2.png"/>

<img src="https://numpy.org/doc/stable/_images/np_MSE_explanation2.png"/>

In fact, there is an even simpler way we could compute this, using the `np.mean()` function:

In [73]:
error = np.mean(np.square(predictions - labels))
error

1.6666666666666667

Of course, the best part about this is, it doesn't matter how much data we have - we could pass arrays of any size into this computation.

## Data types (dtypes)

Finally, let's take a very brief look at some of the different data types that NumPy supports.

At the beginning of this module, we created an array from some existing data values using `np.array()`. 

In [74]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

Because of the data values we provided, NumPy chose an integer data type for us:

In [75]:
data.dtype

dtype('int64')

Earlier, we created an array of zeros using the `np.zeros()` function. 

In [76]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

By default, NumPy created this array with a floating-point data type:

In [77]:
zeros.dtype

dtype('float64')

If we knew we only wanted to store whole numbers, we could have used the `dtype` parameter to override the default, e.g.:

In [78]:
zeros = np.zeros(3, dtype=np.int64)
zeros

array([0, 0, 0])

In [79]:
zeros.dtype

dtype('int64')

Here are all of the integer data types that NumPy supports, along with the range of possible data values for each:

<img src="https://miro.medium.com/max/1400/1*XDBcGPOkqTGd5C7DuRrAiw.png"/>

Here are all of the floating-point data types that NumPy currently supports, along with the range of possible data values for each:

<img src="https://miro.medium.com/max/1400/1*aXnGirp9NLC5oljJ5wGcyA.png"/>

## Further reading

Please see the [NumPy website](https://numpy.org/doc/stable/index.html) for a more complete introduction to NumPy and links to other tutorials and documentation.

For more information about data types, see also [NumPy data types](https://numpy.org/doc/stable/user/basics.types.html) and [A comprehensive guide to NumPy data types](https://betterprogramming.pub/a-comprehensive-guide-to-numpy-data-types-8f62cb57ea83) by Lex Maximov.